# Generated by Django 6.0.1 on 2026-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("createde_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("finish_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
