# Generated by Django 6.0.1 on 2026-02-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="createde_at",
            new_name="created_at",
        ),
    ]
