# Generated by Django 6.0.1 on 2026-02-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_rename_createde_at_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finish_at",
            field=models.DateField(null=True),
        ),
    ]
