# Generated by Django 6.0.1 on 2026-02-04 23:13

import todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_deadline_alter_todo_finish_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(validators=[todos.models.validar_data_futura]),
        ),
    ]
