# Generated by Django 6.0.1 on 2026-02-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["deadline", "created_at"]},
        ),
    ]
